### PR TITLE
Update active-directory-deploying-ws-ad-guidelines.md

### PR DESCRIPTION
**Pull request by tobunka-git**

### CODE REVIEW

**Comment by tobunka-git** [comment]
Polished the language and made some changes to the english version

**Comment by Clarare** [comment]
Hi @tobunka-git , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,
Microsoft C&E Localization Team

**Comment by tobunka-git** [comment]
This change actually follows the one I have made to the English version of this page, which has been accepted.

Try to check!

BTW, i am curious about the procedure for synchronization between different language repos. Can someone here illustrate for me?

**Comment by v-radelg** [comment]
@tobunka-git , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Pull request merged**
